jsaddle/src/Language/Javascript/JSaddle/Run.hs

Fixes a potential memory leak when callbacks are not used

Make callback map updates strict

---

jsaddle/src-ghc/GHCJS/Buffer.hs

While responding to a question on Stack Overflow, I noticed a couple of bugs in `src-ghc/GHCJS/Buffer.hs`.  In `fromByteString`, the helper function is written `h$newByteArrayBase64String`, but the actual name in `Files.hs` is `h$newByteArrayFromBase64String`.  And, in `getUint8Array`, the tag `u3` should be `u8` (again as per `Files.hs`).

Fix a couple of typo-bugs in `Buffer.hs`

---

jsaddle-clib/cbits/include/jsaddle.h
jsaddle-clib/default.nix
jsaddle-clib/jsaddle-clib.cabal
jsaddle-clib/src-ghc/Language/Javascript/JSaddle/CLib.hs
jsaddle-clib/src/Language/Javascript/JSaddle/CLib/Internal.hsc

Added a way to get custom callbacks into the android application for common functionality. So far I've only added the callback for firebase device registration (necessary for push notifications on android) but the data structure and pattern can be extended for all kinds of other app callbacks.
I'll be adding device state transitions next using the same pattern (app opened, app closed, app went to background, app became active, etc).

Add android app callback mechanism

---

jsaddle/default.nix
jsaddle/jsaddle.cabal
jsaddle/src/Language/Javascript/JSaddle/Types.hs

@hamishmack , this would be extremely useful (for example lets us use `async` in JSM) but I do not now if it's safe or not. Specifically I do not know if the functions in `JSContextRef` play well with concurrency.

add `MonadUnliftIO` instance for `JSM`

---

jsaddle-warp/src/Language/Javascript/JSaddle/WebSockets.hs
jsaddle/src/Language/Javascript/JSaddle/Run/Files.hs

This just throws away the 404 responses to GET requests and replaces them with the jsaddle index page. This allows SPAs to be reloaded with the client side route, resulting in the application being served instead of a 404 page.

jsaddle-warp: Render jsaddle page on 404 (for client side routing) (fixes #34)

---

jsaddle-wkwebview/cbits-uikit/AppDelegate.m

Ideally this could be another field in `AppDelegateConfig`, allowing users to take the CString and perform some app specific action when notifications are received.
This is a harmless default action which will allow icon badge number to be updated if the remote notification is received *while the app is in the foreground*. Currently, those are dropped on the floor, and hence the badge updates are ignored and the number can be out of sync with the remote.

Allow badge updates while app is in foreground

---

jsaddle-warp/jsaddle-warp.cabal
jsaddle/jsaddle.cabal

Allows me to use servant 0.13 and thus [reflex-servant](https://github.com/Compositional/reflex-servant/issues/5#issuecomment-383127293).

Bump http-types

---

jsaddle-webkit2gtk/src/Language/Javascript/JSaddle/WebKitGTK.hs
jsaddle-wkwebview/cbits/WKWebView.m
jsaddle-wkwebview/jsaddle-wkwebview.cabal
jsaddle-wkwebview/src/Language/Javascript/JSaddle/WKWebView/Internal.hs

Resolves #59 and should eventually lead to a clean solution for https://github.com/reflex-frp/reflex-platform/issues/209
This should mean that users on Mac will no longer need to generate an empty
index.html to run the app.

Provide a file:// url as a base url for wkwebview

---

jsaddle-warp/src/Language/Javascript/JSaddle/WebSockets.hs

I've just recently started to try to use jsaddle-warp, and was running into segfaults, like so:
```
cabal: repl failed for exe:test-dev from test-0.17.0. The build process
segfaulted (i.e. SIGSEGV).
```
After some digging, it turned out that my app's foreign-store and your jsaddle-warp's store chose the same `Store` number which lead to the above crash.
I didn't test the code in this pull request yet, it's more intended as pseudo-code that may compile, and a way to ask if you are open to fixing this issue this way. Are you? Or would you have a different fix in mind?

Use a higher store number to prevent segfaults

---

jsaddle-wkwebview/default.nix

We need to use xcode_8_2 here from Nixpkgs. The long path is
unfortunate but probably inevitable until someone defines an "iOS sdk"
derivation for Nixpkgs.
/cc @Ericson2314

Fix jsaddle-wkwebview iOS SDK

---

jsaddle-warp/jsaddle-warp.cabal
jsaddle-wkwebview/default.nix

Sorry about the PR spam. The previous version broke some things & also required xcode to build on macOS. This fixes that issue by introducing a hack I had in reflex-platform. No idea how else to fit it.

Fix jsaddle-wkwebview (again)

---

jsaddle-wkwebview/jsaddle-wkwebview.cabal
jsaddle/jsaddle.cabal

allow aeson 1.3.x and exceptions-0.10.x   (in order to be compatible with stack lts-12.3)

allow aeson 1.3.x and exceptions-0.10.x

---

jsaddle-warp/jsaddle-warp.cabal

This is needed to prevent linker errors (especially with profiling).

Add Language.Javascript.JSaddle.WebSockets.Compat to other-modules

---

jsaddle-webkit2gtk/jsaddle-webkit2gtk.cabal

Missed this one in last commit.

jsaddle-webkit2gtk: bump aeson upper bound

---

jsaddle-wkwebview/cbits-cocoa/AppDelegate.m

None of the callbacks in AppDelegateConfig were implemented in wkwebview. This PR adds some of the callbacks to cbits-cocoa (just the ones I needed immediately):
> hs_willFinishLaunchingWithOptions, didFinishLaunchingWithOptions, applicationUniversalLink

Make some callbacks work in wkwebview

---

jsaddle-warp/default.nix
jsaddle-webkit2gtk/default.nix
jsaddle-wkwebview/default.nix
jsaddle/default.nix

The version in `.cabal` files are already bumped, but these in `.nix` files look left in the older one.

Bump version to 0.9.6.0 for Nix

---

jsaddle/src/Language/Javascript/JSaddle/Evaluate.hs
jsaddle/src/Language/Javascript/JSaddle/Object.hs

I think this is a much better default since:
* We define the function-calling function once, therefore
bloat is not a concern;
* The functions accept arbitrary user-provided functions,
and therefore it's dangerous to make assumptions about
their safety.

call functions safely in `(#)`, `jsf`, etc.

---

jsaddle-webkit2gtk/jsaddle-webkit2gtk.cabal
jsaddle-webkit2gtk/src/Language/Javascript/JSaddle/WebKitGTK.hs

javascriptcore-4.0 removed functions related to 'GlobalContext', breaking some existing code. Luckily, we don't need the global context anymore anyway.

jsaddle-webkit2gtk: Update for JavaScriptCore-4.0 api

---

default.nix
jsaddle-wkwebview/default.nix

Newer nixpkgs resulted in errors like:
```
Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_NSURL", referenced from:
objc-class-ref in libHSjsaddle-wkwebview-0.9.6.0-3Qa6qfm5Iv91uqRz8CkhhF.a(WKWebView.o)
ld: symbol(s) not found for architecture x86_64
```
This adds darwin.cf-private which has this symbol, which swift corefoundation lacks.

Fix jsaddle-wkwebview builds

---

jsaddle/src-ghc/JavaScript/Array.hs

Without this, we get `TypeError: jsaddle_values.get(...).apply is not a function` on GHC, but GHCJS works fine.

Fix GHC JavaScript.Array.write

---

jsaddle-warp/src/Language/Javascript/JSaddle/WebSockets.hs

Some things like webpack create the “global” variable so we cannot
rely on just that to detect nodejs systems. To supplement this, we can
also check for the “require” function. This fixes an issue where
require is undefined when using jsaddle-warp.
/cc @hamishmack @Ericson2314

Detect node system better

---

jsaddle-clib/jsaddle-clib.cabal
jsaddle-warp/jsaddle-warp.cabal
jsaddle-webkit2gtk/jsaddle-webkit2gtk.cabal
jsaddle/jsaddle.cabal
jsaddle/src/Language/Javascript/JSaddle/Object.hs

This patch allows building the jsaddle packages with the current stackage nightly.
I wasn't able to build the test suite, since webdriver isn't yet compatible with aeson 2.0, so I haven't been able to verify if the tests still pass.

Fix building with Stackage Nightly 2022-03-03 (ghc-9.0.2) 

---

jsaddle-webkit2gtk/src/Language/Javascript/JSaddle/WebKitGTK.hs

For reasons unknown to me, the type `AsyncReadyCallback` from `GI.Gio.Callback` changed from
```
Maybe Object -> AsyncResult  -> IO ()
```
in gi-gio 2.0.30
```
Maybe Object -> AsyncResult -> Ptr () -> IO ()
```
in gi-gio 2.0.32, without a mention in the changelog. This came up during the update to webkit 2.40 in nixpkgs.
This patch fixes the build of jsaddle-webkit2gtk and I tested an application built with it.
I hope it’s not our job to somehow free the pointer I am ignoring here, but I don’t think so …
It is worth mentioning that `webViewRunJavascript` has a deprecation warning since webkit 2.40.
I didn’t invest more effort in replacing that call since I am unclear what’s going to happen with jsaddle and the ghc new javascript backend.

jsaddle-webkit2gtk: gi-gio 2.0.32 support

---

jsaddle/src-ghc/JavaScript/TypedArray/DataView/Internal.hs

Non-JS targets don't support this extension since GHC 9.8:
https://gitlab.haskell.org/ghc/ghc/-/commit/0350b1865f392cf9590c82b5194b62e63770aa44

Remove unnecessary usage of `JavaScriptFFI`

---

jsaddle/src/Language/Javascript/JSaddle/Run/Files.hs

I have a use case where I would like to run the JSaddle JS glue in a web worker. `window` doesn't exist there, but all the necessary functions are also available in `globalThis`.

Files: use `globalThis`

---

jsaddle-warp/jsaddle-warp.cabal

Looks like #156 missed one entry - fixes an error when building in nixpkgs:
```
Documentation created: dist/doc/html/jsaddle-warp/,
dist/doc/html/jsaddle-warp/jsaddle-warp.txt
Running phase: installPhase
Error: Setup: filepath wildcard 'node-client/node_modules/xmlhttprequest/lib'
does not match any files.
```

Remove dir path from data-files

---

jsaddle-warp/src/Language/Javascript/JSaddle/WebSockets.hs
jsaddle/src/Language/Javascript/JSaddle/Run/Files.hs

It turns out that the original code was relying on V8 specific scoping behavior. The value of the argument `initialSyncDepth` was being set to `1` even when the other arguments inside `runBatch` were being evaluated and eventually calling `runBatch` again. So if I were do make a rough trace:
1. `<some function>`
2. call to `runBatch` with `initialSyncDepth` set to `1`
3. evaluation of `firstBatch` argument of `runBatch`
4. `<some code>`
5. another call to `runBatch` with no `initialSyncDepth` set
^ here is where the difference manifests, in Firefox the value of `initialSyncDepth` as seen by the nested call to `runBatch` will be `undefined`. However in V8 it will be `1` as the call to `runBatch` in 2 is still in progress technically.
This difference would lead to desync between the server …

Fix Firefox compatibility
